steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/container-registry/mlops82-train:$SHORT_SHA',
    '-f',
    'dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/container-registry/mlops82-train:$SHORT_SHA'
  ]

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/container-registry/mlops82-train:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
